// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/goumang.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Method int32

const (
	Method_SHELL Method = 0
)

// Enum value maps for Method.
var (
	Method_name = map[int32]string{
		0: "SHELL",
	}
	Method_value = map[string]int32{
		"SHELL": 0,
	}
)

func (x Method) Enum() *Method {
	p := new(Method)
	*p = x
	return p
}

func (x Method) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Method) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_goumang_proto_enumTypes[0].Descriptor()
}

func (Method) Type() protoreflect.EnumType {
	return &file_proto_goumang_proto_enumTypes[0]
}

func (x Method) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Method.Descriptor instead.
func (Method) EnumDescriptor() ([]byte, []int) {
	return file_proto_goumang_proto_rawDescGZIP(), []int{0}
}

type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        Method                 `protobuf:"varint,1,opt,name=method,proto3,enum=goumang.Method" json:"method,omitempty"`
	MethodParams  string                 `protobuf:"bytes,2,opt,name=method_params,json=methodParams,proto3" json:"method_params,omitempty"`
	Timeout       int32                  `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	RunTaskId     uint64                 `protobuf:"varint,4,opt,name=run_task_id,json=runTaskId,proto3" json:"run_task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_proto_goumang_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goumang_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_goumang_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRequest) GetMethod() Method {
	if x != nil {
		return x.Method
	}
	return Method_SHELL
}

func (x *TaskRequest) GetMethodParams() string {
	if x != nil {
		return x.MethodParams
	}
	return ""
}

func (x *TaskRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *TaskRequest) GetRunTaskId() uint64 {
	if x != nil {
		return x.RunTaskId
	}
	return 0
}

type TaskResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*TaskResponse_Output
	//	*TaskResponse_Error
	Content       isTaskResponse_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_proto_goumang_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goumang_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_goumang_proto_rawDescGZIP(), []int{1}
}

func (x *TaskResponse) GetContent() isTaskResponse_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *TaskResponse) GetOutput() string {
	if x != nil {
		if x, ok := x.Content.(*TaskResponse_Output); ok {
			return x.Output
		}
	}
	return ""
}

func (x *TaskResponse) GetError() string {
	if x != nil {
		if x, ok := x.Content.(*TaskResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isTaskResponse_Content interface {
	isTaskResponse_Content()
}

type TaskResponse_Output struct {
	Output string `protobuf:"bytes,1,opt,name=output,proto3,oneof"`
}

type TaskResponse_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*TaskResponse_Output) isTaskResponse_Content() {}

func (*TaskResponse_Error) isTaskResponse_Content() {}

var File_proto_goumang_proto protoreflect.FileDescriptor

const file_proto_goumang_proto_rawDesc = "" +
	"\n" +
	"\x13proto/goumang.proto\x12\agoumang\"\x95\x01\n" +
	"\vTaskRequest\x12'\n" +
	"\x06method\x18\x01 \x01(\x0e2\x0f.goumang.MethodR\x06method\x12#\n" +
	"\rmethod_params\x18\x02 \x01(\tR\fmethodParams\x12\x18\n" +
	"\atimeout\x18\x03 \x01(\x05R\atimeout\x12\x1e\n" +
	"\vrun_task_id\x18\x04 \x01(\x04R\trunTaskId\"K\n" +
	"\fTaskResponse\x12\x18\n" +
	"\x06output\x18\x01 \x01(\tH\x00R\x06output\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05errorB\t\n" +
	"\acontent*\x13\n" +
	"\x06Method\x12\t\n" +
	"\x05SHELL\x10\x002<\n" +
	"\x04Task\x124\n" +
	"\x03Run\x12\x14.goumang.TaskRequest\x1a\x15.goumang.TaskResponse0\x01B\x1bZ\x19goumang-worker/service/pbb\x06proto3"

var (
	file_proto_goumang_proto_rawDescOnce sync.Once
	file_proto_goumang_proto_rawDescData []byte
)

func file_proto_goumang_proto_rawDescGZIP() []byte {
	file_proto_goumang_proto_rawDescOnce.Do(func() {
		file_proto_goumang_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_goumang_proto_rawDesc), len(file_proto_goumang_proto_rawDesc)))
	})
	return file_proto_goumang_proto_rawDescData
}

var file_proto_goumang_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_goumang_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_goumang_proto_goTypes = []any{
	(Method)(0),          // 0: goumang.Method
	(*TaskRequest)(nil),  // 1: goumang.TaskRequest
	(*TaskResponse)(nil), // 2: goumang.TaskResponse
}
var file_proto_goumang_proto_depIdxs = []int32{
	0, // 0: goumang.TaskRequest.method:type_name -> goumang.Method
	1, // 1: goumang.Task.Run:input_type -> goumang.TaskRequest
	2, // 2: goumang.Task.Run:output_type -> goumang.TaskResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_goumang_proto_init() }
func file_proto_goumang_proto_init() {
	if File_proto_goumang_proto != nil {
		return
	}
	file_proto_goumang_proto_msgTypes[1].OneofWrappers = []any{
		(*TaskResponse_Output)(nil),
		(*TaskResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_goumang_proto_rawDesc), len(file_proto_goumang_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_goumang_proto_goTypes,
		DependencyIndexes: file_proto_goumang_proto_depIdxs,
		EnumInfos:         file_proto_goumang_proto_enumTypes,
		MessageInfos:      file_proto_goumang_proto_msgTypes,
	}.Build()
	File_proto_goumang_proto = out.File
	file_proto_goumang_proto_goTypes = nil
	file_proto_goumang_proto_depIdxs = nil
}
