# 默认安全配置文件
security:
  # 启用命令验证（开发环境可设为 false）
  enableValidation: true

  # 允许的执行路径白名单
  allowedPaths:
    # 示例：应用脚本目录
    - path: "/opt/app/scripts"
      description: "应用脚本目录"
      recursive: true  # 允许子目录
      maxDepth: 10     # 最大子目录深度，0表示只当前目录，-1表示无限制

    # 示例：用户脚本目录
    - path: "/home/scripts"
      description: "用户脚本目录"
      recursive: true
      maxDepth: 3

    # 示例：系统工具目录
    - path: "/usr/local/bin"
      description: "系统工具目录"
      recursive: false  # 只允许当前目录
      maxDepth: 0

  # 允许的命令类型和解释器
  allowedInterpreters:
    # Python 解释器
    - name: "python"
      executables: ["python", "python3", "python3.8", "python3.9", "python3.10", "python3.11"]
      fileExtensions: [".py", ".pyw"]
      description: "Python 脚本执行器"

    # PHP 解释器
    - name: "php"
      executables: ["php", "php8", "php7"]
      fileExtensions: [".php"]
      description: "PHP 脚本执行器"

    # Shell 解释器
    - name: "shell"
      executables: ["bash", "sh", "zsh"]
      fileExtensions: [".sh", ".bash", ".zsh"]
      description: "Shell 脚本执行器"

    # Node.js 解释器
    - name: "node"
      executables: ["node"]
      fileExtensions: [".js"]
      description: "Node.js 脚本执行器"

    # 二进制可执行文件
    - name: "binary"
      executables: []  # 空表示直接执行
      fileExtensions: [""]  # 无扩展名
      description: "二进制可执行文件"

  # 命令解析配置
  commandParsing:
    # 是否允许管道操作
    allowPipes: false
    # 是否允许重定向
    allowRedirection: false
    # 是否允许后台执行 (谨慎开启)
    allowBackground: false
    # 是否允许命令链接 (&&, ||, ;)
    allowChaining: false

  # 危险命令配置
  dangerousCommands:
    # 系统管理类
    sudo: []        # 任何 sudo 都不允许
    su: []          # 任何 su 都不允许
    chown: []       # 任何 chown 都不允许

    # 文件操作类
    rm: []          # 任何 rm 都不允许
    mv: []          # 任何 mv 都不允许
    shred: []       # 任何 shred 都不允许
    wipe: []        # 任何 wipe 都不允许
    dd: []          # 任何 dd 都不允许

    # 权限管理类
    chmod: []       # chmod 配合这些参数不允许

    # 文件系统操作类
    cp: []          # cp 配合这些参数不允许
    ln: []          # ln 配合这些参数不允许

    # 磁盘操作类
    mount: []       # 任何 mount 都不允许
    umount: []      # 任何 umount 都不允许
    fdisk: []       # 任何 fdisk 都不允许
    mkfs: []        # 任何 mkfs 都不允许
    fsck: []        # 任何 fsck 都不允许
    parted: []      # 任何 parted 都不允许
    cfdisk: []      # 任何 cfdisk 都不允许

    # 网络下载和传输（可能下载恶意文件）
    wget: []
    curl: []
    nc: []          # netcat，网络瑞士军刀
    netcat: []
    ncat: []

    # 远程连接和传输
    ssh: []
    scp: []
    rsync: []
    ftp: []
    sftp: []
    telnet: []

    # 进程控制
    kill: []
    killall: []
    pkill: []
    pgrep: []        # 可能泄露进程信息

    # 服务管理
    service:
      - "stop"
      - "restart"
      - "reload"
    systemctl:
      - "stop"
      - "disable"
      - "mask"
      - "restart"

    # 用户管理
    useradd: []
    userdel: []
    usermod: []
    groupadd: []
    groupdel: []
    groupmod: []
    passwd: []

  # 日志配置
  logging:
    # 记录被拒绝的命令
    logDeniedCommands: true
    # 记录允许的命令
    logAllowedCommands: true