# 默认安全配置文件
security:
  # 启用命令验证（开发环境可设为 false）
  enableValidation: true

  # 命令解析配置
  commandParsing:
    # 是否允许管道操作
    allowPipes: false
    # 是否允许重定向
    allowRedirection: false
    # 是否允许命令链接 (&&, ||, ;)
    allowChaining: false

  # 日志配置
  logging:
    # 记录被拒绝的命令
    logDeniedCommands: true
    # 记录允许的命令
    logAllowedCommands: true